### ISSUE TITLE
Corrigir esta linha

### ISSUE THREAD

**Issue by ProfessorUFSC** [EstudanteUFSC/PrimeiroSemestre#3]
https://github.com/EstudanteUFSC/PrimeiroSemestre/blob/67a6bdeeba052915a2308fd21e503010a05cccc1/programacao/prova2/questao1.py#L98

Esta linha precisa ser corrigida comparando as variaveis iguais

**Comment by EstudanteUFSC** [comment]
obrigado professor. linha corrigida.
